version: "3"
services:
  frontend:
    build: frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/cluster2/index.html:/app/index.html
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
  backend:
    build: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/index.js:/app/index.js
    environment:
      NODE_APP_ORIGIN: http://54.177.124.183:8080
      HOCKEY_NODE_HZ_CLOUD_CLUSTER_NAME: bu-1104
      HOCKEY_NODE_HZ_CLOUD_TOKEN: 8VoxSbfRYALH28Ma9mwXNFiTGeVTQOOHDVR7rDcpwr2p6dOFhX



