version: "3"
services:
  backend:
    build: backend
#    networks:
#      - hockey-real-time-stats-network
    ports:
      - "3000:3000"
    volumes:
      - ./backend/index.js:/app/index.js
#  frontend:
#    build: frontend
#    networks:
#      - hockey-real-time-stats-network
#    ports:
#      - "127.0.0.1:8080:8080"
#    volumes:
#      - ./frontend/index.html:/app/index.html
#      - ./frontend/package.json:/app/package.json
#      - ./frontend/package-lock.json:/app/package-lock.json


#networks:
#  hockey-real-time-stats-network:

